### ISSUE TITLE
Failing tests should report expected and received values

### ISSUE THREAD

**Issue by jelkner** [NateLevin1/ctest#1] opened 2024-02-19 12:36 UTC
When a test fails, it just reports something like:
```
Failed: list_length(mylist) != 11
```
It would be most helpful if it also reported the value it did receive, something like:
```
Failed: list_length(mylist) expected 11 received 10
```

**Comment by NateLevin1** [comment] 2024-02-19 18:17
The problem is that we don't know the correct formatting specifier to do this - that's why the `RETURNS_***` functions are able to have prettier output, but `ASSERT`s are not.

I've discovered [C11's `_Generic` feature](https://dev.to/pauljlucas/generic-in-c-i48), which looks like it might allow us to have this behavior. I can look into it next class.

**Comment by NateLevin1** [comment] 2024-02-21 01:52
I've implemented a prototype in https://github.com/NateLevin1/ctest/commit/80af3388b6126ecd554050981b5ddac2961b8327 — going to close this issue & we will talk about it next class.

**Closed as completed by NateLevin1** 2024-02-21 01:52 UTC
